# action.yml
name: 'Revert Commit Action'
description: 'Automatically revert a given commit'
inputs:
  github-token:
    description: 'Github Action generated secret token for authentication purposes'
    required: true
  is-push-enabled:
    description: 'Parameter to enable or disable the push of the revert (defaulting to false for safety/testing).'
    required: true
    default: 'false'
outputs:
  start-time:
    description: 'The time the github action started'
branding:
    icon: 'rewind'
    color: 'red'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    IS_PUSH_ENABLED: ${{ inputs.is-push-enabled }}
